"""YOLO model training utilities for retail fixture detection."""

import json
import logging
import os
import random
import time
from typing import Optional

from server.database import execute_query, execute_update, get_workspace_client

logger = logging.getLogger(__name__)

CATALOG = "jsf_demo_catalog"
SCHEMA = "scenic_crawler"
TRAINING_VOLUME = f"/Volumes/{CATALOG}/{SCHEMA}/training_images"
DATASET_VOLUME = f"/Volumes/{CATALOG}/{SCHEMA}/yolo_datasets"
MODELS_VOLUME = f"/Volumes/{CATALOG}/{SCHEMA}/trained_models"


def export_yolo_dataset(output_volume_path: Optional[str] = None) -> str:
    """Export all training images + annotations from DB to YOLO format in a Volume.

    Creates:
      {output}/images/train/  images/val/
      {output}/labels/train/  labels/val/
      {output}/data.yaml

    Returns the output volume path.
    """
    if not output_volume_path:
        run_id = int(time.time() * 1000)
        output_volume_path = f"{DATASET_VOLUME}/dataset_{run_id}"

    w = get_workspace_client()

    # Load fixture types for class mapping
    fixture_rows = execute_query("SELECT name FROM fixture_types ORDER BY name")
    class_names = [r["name"] for r in fixture_rows]
    class_map = {name: idx for idx, name in enumerate(class_names)}

    # Load all images that have at least one annotation
    images = execute_query("""
        SELECT ti.image_id, ti.filename, ti.volume_path, ti.width, ti.height
        FROM training_images ti
        WHERE ti.annotation_count > 0
        ORDER BY ti.image_id
    """)

    if not images:
        raise ValueError("No annotated images found for export")

    # Shuffle and split 80/20
    random.shuffle(images)
    split_idx = max(1, int(len(images) * 0.8))
    train_images = images[:split_idx]
    val_images = images[split_idx:] if split_idx < len(images) else images[-1:]

    def _upload_bytes(path: str, data: bytes):
        import io
        w.files.upload(path, io.BytesIO(data), overwrite=True)

    def _copy_image_and_labels(img_list: list[dict], subset: str):
        for img in img_list:
            # Copy image file
            src_path = img["volume_path"]
            fname = img["filename"]
            dst_image_path = f"{output_volume_path}/images/{subset}/{fname}"

            try:
                resp = w.files.download(src_path)
                image_bytes = resp.contents.read()
                _upload_bytes(dst_image_path, image_bytes)
            except Exception as e:
                logger.warning(f"Failed to copy image {fname}: {e}")
                continue

            # Build YOLO label file
            annotations = execute_query("""
                SELECT fixture_type, x_center, y_center, width, height
                FROM training_annotations
                WHERE image_id = %(iid)s
            """, {"iid": img["image_id"]})

            label_lines = []
            for ann in annotations:
                cls_id = class_map.get(ann["fixture_type"])
                if cls_id is None:
                    continue
                # Annotations are stored as percentages 0-100, YOLO needs 0-1
                x_c = float(ann["x_center"]) / 100.0
                y_c = float(ann["y_center"]) / 100.0
                w_n = float(ann["width"]) / 100.0
                h_n = float(ann["height"]) / 100.0
                label_lines.append(f"{cls_id} {x_c:.6f} {y_c:.6f} {w_n:.6f} {h_n:.6f}")

            label_fname = os.path.splitext(fname)[0] + ".txt"
            dst_label_path = f"{output_volume_path}/labels/{subset}/{label_fname}"
            label_content = "\n".join(label_lines)
            _upload_bytes(dst_label_path, label_content.encode("utf-8"))

    logger.info(f"Exporting YOLO dataset: {len(train_images)} train, {len(val_images)} val")
    _copy_image_and_labels(train_images, "train")
    _copy_image_and_labels(val_images, "val")

    # Create data.yaml
    data_yaml = (
        f"path: {output_volume_path}\n"
        f"train: images/train\n"
        f"val: images/val\n"
        f"\n"
        f"nc: {len(class_names)}\n"
        f"names: {json.dumps(class_names)}\n"
    )
    _upload_bytes(f"{output_volume_path}/data.yaml", data_yaml.encode("utf-8"))

    logger.info(f"YOLO dataset exported to {output_volume_path}")
    return output_volume_path


def generate_training_script(
    dataset_path: str,
    model_size: str = "n",
    epochs: int = 50,
    batch_size: int = 16,
) -> str:
    """Generate a Python training script string for YOLOv8.

    The script installs ultralytics, trains the model, saves metrics as JSON,
    and logs the model to MLflow.
    """
    results_ts = int(time.time() * 1000)
    results_path = f"{MODELS_VOLUME}/results_{results_ts}"

    # Use raw string to avoid f-string escaping nightmares
    # Inject values via str.replace after
    script_template = r'''#!/usr/bin/env python3
"""YOLO training script - auto-generated by Inventario Inteligente."""
import subprocess, sys, json, os, shutil

# Install deps
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "ultralytics", "mlflow", "pyyaml"])

from ultralytics import YOLO
import mlflow
from databricks.sdk import WorkspaceClient

# --- Configuration (injected at generation time) ---
VOLUME_DATASET = "__DATASET_PATH__"
MODEL_SIZE = "__MODEL_SIZE__"
EPOCHS = __EPOCHS__
BATCH_SIZE = __BATCH_SIZE__
VOLUME_RESULTS = "__RESULTS_PATH__"
LOCAL_DATASET = "/tmp/yolo_dataset"
LOCAL_RESULTS = "/tmp/yolo_results"

print(f"Config: model=yolov8{MODEL_SIZE}, epochs={EPOCHS}, batch={BATCH_SIZE}")
print(f"Volume dataset: {VOLUME_DATASET}")

# --- Step 1: Copy dataset from Volume to local /tmp ---
print("Step 1: Downloading dataset from Volume...")
if os.path.exists(LOCAL_DATASET):
    shutil.rmtree(LOCAL_DATASET)

w = WorkspaceClient()

def dl_dir(vol_path, local_path):
    os.makedirs(local_path, exist_ok=True)
    for entry in w.files.list_directory_contents(vol_path):
        name = entry.path.split("/")[-1]
        remote = entry.path
        local = os.path.join(local_path, name)
        if entry.is_directory:
            dl_dir(remote, local)
        else:
            resp = w.files.download(remote)
            with open(local, "wb") as f:
                f.write(resp.contents.read())
            print(f"  {name}")

dl_dir(VOLUME_DATASET, LOCAL_DATASET)

# Fix data.yaml paths
import yaml
yaml_path = os.path.join(LOCAL_DATASET, "data.yaml")
with open(yaml_path) as f:
    cfg = yaml.safe_load(f)
cfg["path"] = LOCAL_DATASET
cfg["train"] = "images/train"
cfg["val"] = "images/val"
with open(yaml_path, "w") as f:
    yaml.dump(cfg, f)
print(f"Dataset ready at {LOCAL_DATASET}")

# --- Step 2: Train ---
print("Step 2: Training...")
mlflow.set_experiment("/Shared/inventario-inteligente/yolo-training")

with mlflow.start_run(run_name=f"yolov8{MODEL_SIZE}_e{EPOCHS}_b{BATCH_SIZE}") as run:
    mlflow.log_params({"model_size": MODEL_SIZE, "epochs": EPOCHS, "batch_size": BATCH_SIZE})

    model = YOLO(f"yolov8{MODEL_SIZE}.pt")
    results = model.train(
        data=yaml_path, epochs=EPOCHS, batch=BATCH_SIZE,
        imgsz=640, project=LOCAL_RESULTS, name="train",
        exist_ok=True, verbose=True,
    )

    # Extract metrics
    metrics = {}
    try:
        rd = results.results_dict
        metrics["map50"] = float(rd.get("metrics/mAP50(B)", 0))
        metrics["map50_95"] = float(rd.get("metrics/mAP50-95(B)", 0))
        metrics["precision"] = float(rd.get("metrics/precision(B)", 0))
        metrics["recall"] = float(rd.get("metrics/recall(B)", 0))
    except Exception as e:
        print(f"Metric extraction warning: {e}")

    try:
        if hasattr(results, "names") and hasattr(results, "maps"):
            metrics["per_class"] = {results.names[i]: float(results.maps[i]) for i in results.names if i < len(results.maps)}
    except Exception:
        pass

    for k, v in metrics.items():
        if isinstance(v, (int, float)):
            mlflow.log_metric(k, v)

    # Log artifacts
    train_dir = os.path.join(LOCAL_RESULTS, "train")
    for artifact in ["weights/best.pt", "confusion_matrix.png", "results.png"]:
        p = os.path.join(train_dir, artifact)
        if os.path.exists(p):
            mlflow.log_artifact(p)

    # --- Step 3: Copy results to Volume ---
    print("Step 3: Uploading results to Volume...")
    metrics["mlflow_run_id"] = run.info.run_id
    metrics["best_model_path"] = f"{VOLUME_RESULTS}/train/weights/best.pt"

    # Save metrics.json locally
    mj = os.path.join(train_dir, "metrics.json")
    with open(mj, "w") as f:
        json.dump(metrics, f, indent=2)

    # Upload key files
    for fname in ["metrics.json", "weights/best.pt", "weights/last.pt", "confusion_matrix.png", "results.png"]:
        src = os.path.join(train_dir, fname)
        if os.path.exists(src):
            dst = f"{VOLUME_RESULTS}/train/{fname}"
            try:
                with open(src, "rb") as fh:
                    w.files.upload(dst, fh, overwrite=True)
                print(f"  Uploaded: {fname}")
            except Exception as e:
                print(f"  Failed: {fname} - {e}")

    print(f"Done! Metrics: {json.dumps(metrics, indent=2)}")
'''
    # Inject actual values (no f-string escaping issues)
    script = script_template
    script = script.replace("__DATASET_PATH__", dataset_path)
    script = script.replace("__MODEL_SIZE__", model_size)
    script = script.replace("__EPOCHS__", str(epochs))
    script = script.replace("__BATCH_SIZE__", str(batch_size))
    script = script.replace("__RESULTS_PATH__", results_path)

    return script, results_path


def parse_training_results(results_path: str) -> dict:
    """Parse YOLO training output and return dict with metrics."""
    w = get_workspace_client()
    metrics_file = f"{results_path}/train/metrics.json"

    try:
        resp = w.files.download(metrics_file)
        content = resp.contents.read().decode("utf-8")
        metrics = json.loads(content)
        return metrics
    except Exception as e:
        logger.warning(f"Could not parse training results from {metrics_file}: {e}")
        return {}


def _get_auth_headers(w) -> tuple[str, str]:
    """Get host and Bearer token from workspace client for REST API calls."""
    host = w.config.host.rstrip("/")
    headers = w.config.authenticate()
    token = headers.get("Authorization", "").replace("Bearer ", "") if headers else ""
    return host, token


def _databricks_rest_get(w, path: str) -> dict:
    """Make an authenticated GET request to Databricks REST API."""
    import json as _json
    import urllib.request
    import ssl
    try:
        ssl._create_default_https_context = ssl._create_unverified_context
    except Exception:
        pass

    host, token = _get_auth_headers(w)
    req = urllib.request.Request(
        f"{host}{path}",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        method="GET",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return _json.loads(resp.read())


def _databricks_rest_post(w, path: str, payload: dict) -> dict:
    """Make an authenticated POST request to Databricks REST API."""
    import json as _json
    import urllib.request
    import ssl
    try:
        ssl._create_default_https_context = ssl._create_unverified_context
    except Exception:
        pass

    host, token = _get_auth_headers(w)
    data = _json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"{host}{path}",
        data=data,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return _json.loads(resp.read())


def get_run_status(w, run_id: int) -> dict:
    """Get the status of a Databricks job run via REST API.

    Returns dict with keys: life_cycle_state, result_state, state_message.
    """
    result = _databricks_rest_get(w, f"/api/2.1/jobs/runs/get?run_id={run_id}")
    state = result.get("state", {})
    status = result.get("status", {})
    return {
        "life_cycle_state": state.get("life_cycle_state", "UNKNOWN"),
        "result_state": state.get("result_state"),
        "state_message": state.get("state_message", ""),
        "termination_code": status.get("termination_details", {}).get("code", ""),
        "termination_message": status.get("termination_details", {}).get("message", ""),
    }


def submit_training_job(
    w,
    script: str,
    cluster_spec: Optional[dict] = None,
) -> int:
    """Submit a Databricks Job using workspace client.

    Uploads the training script to /Workspace/Shared/ (more reliable than
    Volumes for spark_python_task) and submits a one-time run via REST API.

    Returns the Databricks run_id.
    """
    # Default cluster spec with GPU for YOLO training
    if cluster_spec is None:
        cluster_spec = {
            "spark_version": "15.4.x-gpu-ml-scala2.12",
            "num_workers": 0,
            "node_type_id": "g5.xlarge",
            "driver_node_type_id": "g5.xlarge",
        }

    # Upload script to DBFS (the only reliable path for spark_python_task)
    import io
    import base64
    import json as _json
    import urllib.request
    import ssl
    try:
        ssl._create_default_https_context = ssl._create_unverified_context
    except Exception:
        pass

    script_ts = int(time.time() * 1000)
    dbfs_path = f"dbfs:/inventario-inteligente/training_scripts/train_{script_ts}.py"
    script_path = dbfs_path  # for spark_python_task

    host, token = _get_auth_headers(w)

    # Upload to DBFS via REST API (handles files up to 1MB inline)
    script_b64 = base64.b64encode(script.encode("utf-8")).decode("utf-8")
    put_payload = _json.dumps({
        "path": dbfs_path.replace("dbfs:", ""),
        "contents": script_b64,
        "overwrite": True,
    }).encode("utf-8")
    put_req = urllib.request.Request(
        f"{host}/api/2.0/dbfs/put",
        data=put_payload,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(put_req, timeout=30) as resp:
        resp.read()

    logger.info(f"Uploaded training script to {script_path}")

    # Submit as a one-time run via REST API
    result = _databricks_rest_post(w, "/api/2.1/jobs/runs/submit", {
        "run_name": f"YOLO Training {int(time.time())}",
        "tasks": [{
            "task_key": "yolo_train",
            "new_cluster": cluster_spec,
            "spark_python_task": {
                "python_file": script_path,
            },
        }],
    })
    run_id = result.get("run_id")

    logger.info(f"Submitted Databricks training job, run_id={run_id}")
    return run_id
