"""YOLO model training utilities for retail fixture detection."""

import json
import logging
import os
import random
import time
from typing import Optional

from server.database import execute_query, execute_update, get_workspace_client

logger = logging.getLogger(__name__)

CATALOG = "jsf_demo_catalog"
SCHEMA = "scenic_crawler"
TRAINING_VOLUME = f"/Volumes/{CATALOG}/{SCHEMA}/training_images"
DATASET_VOLUME = f"/Volumes/{CATALOG}/{SCHEMA}/yolo_datasets"
MODELS_VOLUME = f"/Volumes/{CATALOG}/{SCHEMA}/trained_models"


def export_yolo_dataset(output_volume_path: Optional[str] = None) -> str:
    """Export all training images + annotations from DB to YOLO format in a Volume.

    Creates:
      {output}/images/train/  images/val/
      {output}/labels/train/  labels/val/
      {output}/data.yaml

    Returns the output volume path.
    """
    if not output_volume_path:
        run_id = int(time.time() * 1000)
        output_volume_path = f"{DATASET_VOLUME}/dataset_{run_id}"

    w = get_workspace_client()

    # Load fixture types for class mapping
    fixture_rows = execute_query("SELECT name FROM fixture_types ORDER BY name")
    class_names = [r["name"] for r in fixture_rows]
    class_map = {name: idx for idx, name in enumerate(class_names)}

    # Load all images that have at least one annotation
    images = execute_query("""
        SELECT ti.image_id, ti.filename, ti.volume_path, ti.width, ti.height
        FROM training_images ti
        WHERE ti.annotation_count > 0
        ORDER BY ti.image_id
    """)

    if not images:
        raise ValueError("No annotated images found for export")

    # Shuffle and split 80/20
    random.shuffle(images)
    split_idx = max(1, int(len(images) * 0.8))
    train_images = images[:split_idx]
    val_images = images[split_idx:] if split_idx < len(images) else images[-1:]

    def _upload_bytes(path: str, data: bytes):
        import io
        w.files.upload(path, io.BytesIO(data), overwrite=True)

    def _copy_image_and_labels(img_list: list[dict], subset: str):
        for img in img_list:
            # Copy image file
            src_path = img["volume_path"]
            fname = img["filename"]
            dst_image_path = f"{output_volume_path}/images/{subset}/{fname}"

            try:
                resp = w.files.download(src_path)
                image_bytes = resp.contents.read()
                _upload_bytes(dst_image_path, image_bytes)
            except Exception as e:
                logger.warning(f"Failed to copy image {fname}: {e}")
                continue

            # Build YOLO label file
            annotations = execute_query("""
                SELECT fixture_type, x_center, y_center, width, height
                FROM training_annotations
                WHERE image_id = %(iid)s
            """, {"iid": img["image_id"]})

            label_lines = []
            for ann in annotations:
                cls_id = class_map.get(ann["fixture_type"])
                if cls_id is None:
                    continue
                # Annotations are stored as percentages 0-100, YOLO needs 0-1
                x_c = float(ann["x_center"]) / 100.0
                y_c = float(ann["y_center"]) / 100.0
                w_n = float(ann["width"]) / 100.0
                h_n = float(ann["height"]) / 100.0
                label_lines.append(f"{cls_id} {x_c:.6f} {y_c:.6f} {w_n:.6f} {h_n:.6f}")

            label_fname = os.path.splitext(fname)[0] + ".txt"
            dst_label_path = f"{output_volume_path}/labels/{subset}/{label_fname}"
            label_content = "\n".join(label_lines)
            _upload_bytes(dst_label_path, label_content.encode("utf-8"))

    logger.info(f"Exporting YOLO dataset: {len(train_images)} train, {len(val_images)} val")
    _copy_image_and_labels(train_images, "train")
    _copy_image_and_labels(val_images, "val")

    # Create data.yaml
    data_yaml = (
        f"path: {output_volume_path}\n"
        f"train: images/train\n"
        f"val: images/val\n"
        f"\n"
        f"nc: {len(class_names)}\n"
        f"names: {json.dumps(class_names)}\n"
    )
    _upload_bytes(f"{output_volume_path}/data.yaml", data_yaml.encode("utf-8"))

    logger.info(f"YOLO dataset exported to {output_volume_path}")
    return output_volume_path


def generate_training_script(
    dataset_path: str,
    model_size: str = "n",
    epochs: int = 50,
    batch_size: int = 16,
) -> str:
    """Generate a Python training script string for YOLOv8.

    The script installs ultralytics, trains the model, saves metrics as JSON,
    and logs the model to MLflow.
    """
    results_ts = int(time.time() * 1000)
    results_path = f"{MODELS_VOLUME}/results_{results_ts}"

    script = f'''#!/usr/bin/env python3
"""YOLO training script - auto-generated by Inventario Inteligente."""

import subprocess
import sys
import json
import os
import shutil

# Install dependencies
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "ultralytics", "mlflow", "pyyaml"])

from ultralytics import YOLO
import mlflow

# Configuration
VOLUME_DATASET = "{dataset_path}"
MODEL_SIZE = "{model_size}"
EPOCHS = {epochs}
BATCH_SIZE = {batch_size}
VOLUME_RESULTS_PATH = "{results_path}"
LOCAL_DATASET = "/tmp/yolo_dataset"
LOCAL_RESULTS = "/tmp/yolo_results"

print(f"Starting YOLO training: model=yolov8{{MODEL_SIZE}}, epochs={{EPOCHS}}, batch={{BATCH_SIZE}}")
print(f"Volume dataset: {{VOLUME_DATASET}}")

# Copy dataset from Volume to local /tmp using Databricks SDK
# (shutil.copytree and direct file reads don't work on Volumes in GPU clusters)
print("Copying dataset to local disk via SDK...")
if os.path.exists(LOCAL_DATASET):
    shutil.rmtree(LOCAL_DATASET)

from databricks.sdk import WorkspaceClient
_w = WorkspaceClient()

def download_volume_dir(volume_path, local_path):
    os.makedirs(local_path, exist_ok=True)
    entries = list(_w.files.list_directory_contents(volume_path))
    for entry in entries:
        name = entry.path.split("/")[-1] if hasattr(entry, "path") else str(entry)
        remote = f"{{volume_path}}/{{name}}" if not hasattr(entry, "path") else entry.path
        local = os.path.join(local_path, name)
        if getattr(entry, "is_directory", False):
            download_volume_dir(remote, local)
        else:
            try:
                resp = _w.files.download(remote)
                with open(local, "wb") as f:
                    f.write(resp.contents.read())
            except Exception as e:
                print(f"  Warning: could not download {{name}}: {{e}}")

download_volume_dir(VOLUME_DATASET, LOCAL_DATASET)
print(f"Dataset copied to: {{LOCAL_DATASET}}")

# Fix data.yaml paths to use local copy
import yaml
data_yaml_path = os.path.join(LOCAL_DATASET, "data.yaml")
with open(data_yaml_path, "r") as f:
    data_cfg = yaml.safe_load(f)
data_cfg["train"] = os.path.join(LOCAL_DATASET, "images", "train")
data_cfg["val"] = os.path.join(LOCAL_DATASET, "images", "val")
with open(data_yaml_path, "w") as f:
    yaml.dump(data_cfg, f)

DATA_YAML = data_yaml_path

# Set up MLflow
mlflow.set_experiment("/Shared/inventario-inteligente/yolo-training")

with mlflow.start_run(run_name=f"yolov8{{MODEL_SIZE}}_e{{EPOCHS}}_b{{BATCH_SIZE}}") as run:
    mlflow.log_params({{
        "model_size": MODEL_SIZE,
        "epochs": EPOCHS,
        "batch_size": BATCH_SIZE,
        "dataset_path": DATASET_PATH,
    }})

    # Load pre-trained model
    model = YOLO(f"yolov8{{MODEL_SIZE}}.pt")

    # Train locally (Volumes don't support mkdir from YOLO)
    results = model.train(
        data=DATA_YAML,
        epochs=EPOCHS,
        batch=BATCH_SIZE,
        imgsz=640,
        project=LOCAL_RESULTS,
        name="train",
        exist_ok=True,
        verbose=True,
    )

    # Extract metrics
    metrics = {{}}
    try:
        metrics["map50"] = float(results.results_dict.get("metrics/mAP50(B)", 0))
        metrics["map50_95"] = float(results.results_dict.get("metrics/mAP50-95(B)", 0))
        metrics["precision"] = float(results.results_dict.get("metrics/precision(B)", 0))
        metrics["recall"] = float(results.results_dict.get("metrics/recall(B)", 0))
    except Exception as e:
        print(f"Warning: could not extract all metrics: {{e}}")

    # Try to extract confusion matrix
    try:
        cm_path = os.path.join(LOCAL_RESULTS, "train", "confusion_matrix.png")
        if os.path.exists(cm_path):
            mlflow.log_artifact(cm_path)
    except Exception as e:
        print(f"Warning: could not log confusion matrix: {{e}}")

    # Try per-class metrics
    try:
        if hasattr(results, "names") and hasattr(results, "maps"):
            per_class = {{}}
            for i, name in results.names.items():
                per_class[name] = float(results.maps[i]) if i < len(results.maps) else 0.0
            metrics["per_class_map50_95"] = per_class
    except Exception:
        pass

    # Log metrics to MLflow
    for k, v in metrics.items():
        if isinstance(v, (int, float)):
            mlflow.log_metric(k, v)

    # Log best model
    best_model_local = os.path.join(LOCAL_RESULTS, "train", "weights", "best.pt")
    if os.path.exists(best_model_local):
        mlflow.log_artifact(best_model_local)
        print(f"Best model: {{best_model_local}}")

    # Copy key results to Volume for the app to read
    print(f"Copying results to Volume: {{VOLUME_RESULTS_PATH}}")
    from databricks.sdk import WorkspaceClient
    w = WorkspaceClient()
    for fname in ["metrics.json", "weights/best.pt", "weights/last.pt", "confusion_matrix.png", "results.png"]:
        local_f = os.path.join(LOCAL_RESULTS, "train", fname)
        if os.path.exists(local_f):
            vol_f = f"{{VOLUME_RESULTS_PATH}}/train/{{fname}}"
            try:
                with open(local_f, "rb") as fh:
                    w.files.upload(vol_f, fh, overwrite=True)
                print(f"  Copied: {{fname}}")
            except Exception as e:
                print(f"  Failed to copy {{fname}}: {{e}}")

    # Save metrics JSON locally then copy
    metrics["mlflow_run_id"] = run.info.run_id
    metrics["best_model_path"] = f"{{VOLUME_RESULTS_PATH}}/train/weights/best.pt"

    metrics_local = os.path.join(LOCAL_RESULTS, "train", "metrics.json")
    os.makedirs(os.path.dirname(metrics_local), exist_ok=True)
    with open(metrics_local, "w") as f:
        json.dump(metrics, f, indent=2)

    # Upload metrics.json to Volume
    try:
        with open(metrics_local, "rb") as fh:
            w.files.upload(f"{{VOLUME_RESULTS_PATH}}/train/metrics.json", fh, overwrite=True)
    except Exception as e:
        print(f"Failed to upload metrics.json: {{e}}")

    print(f"Training complete. Metrics: {{json.dumps(metrics, indent=2)}}")
'''
    return script, results_path


def parse_training_results(results_path: str) -> dict:
    """Parse YOLO training output and return dict with metrics."""
    w = get_workspace_client()
    metrics_file = f"{results_path}/train/metrics.json"

    try:
        resp = w.files.download(metrics_file)
        content = resp.contents.read().decode("utf-8")
        metrics = json.loads(content)
        return metrics
    except Exception as e:
        logger.warning(f"Could not parse training results from {metrics_file}: {e}")
        return {}


def _get_auth_headers(w) -> tuple[str, str]:
    """Get host and Bearer token from workspace client for REST API calls."""
    host = w.config.host.rstrip("/")
    headers = w.config.authenticate()
    token = headers.get("Authorization", "").replace("Bearer ", "") if headers else ""
    return host, token


def _databricks_rest_get(w, path: str) -> dict:
    """Make an authenticated GET request to Databricks REST API."""
    import json as _json
    import urllib.request
    import ssl
    try:
        ssl._create_default_https_context = ssl._create_unverified_context
    except Exception:
        pass

    host, token = _get_auth_headers(w)
    req = urllib.request.Request(
        f"{host}{path}",
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        method="GET",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return _json.loads(resp.read())


def _databricks_rest_post(w, path: str, payload: dict) -> dict:
    """Make an authenticated POST request to Databricks REST API."""
    import json as _json
    import urllib.request
    import ssl
    try:
        ssl._create_default_https_context = ssl._create_unverified_context
    except Exception:
        pass

    host, token = _get_auth_headers(w)
    data = _json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        f"{host}{path}",
        data=data,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return _json.loads(resp.read())


def get_run_status(w, run_id: int) -> dict:
    """Get the status of a Databricks job run via REST API.

    Returns dict with keys: life_cycle_state, result_state, state_message.
    """
    result = _databricks_rest_get(w, f"/api/2.1/jobs/runs/get?run_id={run_id}")
    state = result.get("state", {})
    status = result.get("status", {})
    return {
        "life_cycle_state": state.get("life_cycle_state", "UNKNOWN"),
        "result_state": state.get("result_state"),
        "state_message": state.get("state_message", ""),
        "termination_code": status.get("termination_details", {}).get("code", ""),
        "termination_message": status.get("termination_details", {}).get("message", ""),
    }


def submit_training_job(
    w,
    script: str,
    cluster_spec: Optional[dict] = None,
) -> int:
    """Submit a Databricks Job using workspace client.

    Uploads the training script to /Workspace/Shared/ (more reliable than
    Volumes for spark_python_task) and submits a one-time run via REST API.

    Returns the Databricks run_id.
    """
    # Default cluster spec with GPU for YOLO training
    if cluster_spec is None:
        cluster_spec = {
            "spark_version": "15.4.x-gpu-ml-scala2.12",
            "num_workers": 0,
            "node_type_id": "g5.xlarge",
            "driver_node_type_id": "g5.xlarge",
        }

    # Upload script to DBFS (the only reliable path for spark_python_task)
    import io
    import base64
    import json as _json
    import urllib.request
    import ssl
    try:
        ssl._create_default_https_context = ssl._create_unverified_context
    except Exception:
        pass

    script_ts = int(time.time() * 1000)
    dbfs_path = f"dbfs:/inventario-inteligente/training_scripts/train_{script_ts}.py"
    script_path = dbfs_path  # for spark_python_task

    host, token = _get_auth_headers(w)

    # Upload to DBFS via REST API (handles files up to 1MB inline)
    script_b64 = base64.b64encode(script.encode("utf-8")).decode("utf-8")
    put_payload = _json.dumps({
        "path": dbfs_path.replace("dbfs:", ""),
        "contents": script_b64,
        "overwrite": True,
    }).encode("utf-8")
    put_req = urllib.request.Request(
        f"{host}/api/2.0/dbfs/put",
        data=put_payload,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(put_req, timeout=30) as resp:
        resp.read()

    logger.info(f"Uploaded training script to {script_path}")

    # Submit as a one-time run via REST API
    result = _databricks_rest_post(w, "/api/2.1/jobs/runs/submit", {
        "run_name": f"YOLO Training {int(time.time())}",
        "tasks": [{
            "task_key": "yolo_train",
            "new_cluster": cluster_spec,
            "spark_python_task": {
                "python_file": script_path,
            },
        }],
    })
    run_id = result.get("run_id")

    logger.info(f"Submitted Databricks training job, run_id={run_id}")
    return run_id
